version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: my_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: box_organizer
      MYSQL_USER: appUser
      MYSQL_PASSWORD: myPass
    ports:
      - "3306:3306"