version: '3'

networks:
    box-organizer-network:
      driver: bridge

services:
  mysql:
    image: mysql:latest
    container_name: my_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: box_organizer
      MYSQL_USER: appUser
      MYSQL_PASSWORD: myPass
    ports:
      - "3306:3306"
    networks:
      - box-organizer-network
  box-organizer:
    image: rgs0712/box-organizer:latest
    container_name: box-organizer
    ports:
      - "8080:8080"
    networks:
      - box-organizer-network